path = /import/linux/home1/clow1/Documents/cs442/Crystal_Low_assign2/studentCoursePlanner/

all:

run:
	ant -buildfile studentCoursePlanner/src/build.xml run -Darg0="$(path)input1.txt" -Darg1="$(path)output1.txt"

build:
	ant -buildfile studentCoursePlanner/src/build.xml

clean:
	 ant -buildfile studentCoursePlanner/src/build.xml clean