path = /import/linux/home1/clow1/Documents/cs442/Crystal_Low_assign3/dynamicLoadBalancer/

all:

run:
	ant -buildfile dynamicLoadBalancer/src/build.xml run -Darg0="$(path)input.txt" -Darg1="$(path)output1.txt"

build:
	ant -buildfile dynamicLoadBalancer/src/build.xml

clean:
	 ant -buildfile dynamicLoadBalancer/src/build.xml clean